# Generated by Django 4.1 on 2022-10-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerprofile',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
