# Generated by Django 4.1 on 2022-11-01 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 1, 22, 30, 44, 68036)),
        ),
    ]
