# Generated by Django 4.1 on 2022-11-02 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 2, 10, 21, 6, 548394)),
        ),
    ]
