# Generated by Django 4.1 on 2022-12-03 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 11, 11, 7, 800140)),
        ),
    ]
