# Generated by Django 4.1 on 2022-12-12 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 12, 10, 58, 13, 841728)),
        ),
    ]
